### ISSUE TITLE
Server disconnect menu item deleting .json server configuration

### ISSUE THREAD

**Issue by christer88** [thelounge/thelounge#1112]
![disconnect button](https://cloud.githubusercontent.com/assets/11909212/25550677/6ca2c0fe-2c7b-11e7-9086-407beed57462.PNG)

Majority of people seeing a menu item named "Disconnect" when clicking on the server in the channel list think this is to disconnect - ergo disconnect from the server and possibly remove it from the channel list until Lounge is started again or you type /server <server ip>.

What actualy happens is removal of .json server configuration. This is a missmatch between what the majority of people expect to happen and can lead to loss of server configurations including NickServ passwords and more.

I suggest: Turn "Disconnect" into disconnecting you from the server and remove it from the channel list until Lounge is started again or you type /server <server ip>. New menu item named "Remove server" remove .json server configuration.

**Comment by astorije** [comment]
This button should be something like `Disconnect & Remove` or some better wording, but 👎 on disconnecting until the server is started again. Users should never care about when a server restarts (even though they do now re: scrollback loading 😅).

So it should be a straightforward change assuming we agree on the wording. @xPaw, thoughts?

**Comment by christer88** [comment]
29.04.2017 on #thelounge IRC channel:

20:00   +xPaw   that's a poorly named button, it should be 'Remove' or something
20:00   fnutt   I cannot close a network in TheLounge without all the configuration is getting deleted?
20:00   +xPaw   send a /quit
20:00   fnutt   Delete network from config
20:00   fnutt   That's what it does.
20:00   fnutt   Disconnect should be /quit. :p
20:01   +xPaw   err, what the shit
20:03   +xPaw   well then, there's a /disconnect command a /quit command with different implementations

**Comment by starquake** [comment]
Oh so this is why my config is disappearing all the time. I had issues on a server where I couldn't connect to a channel because "I had already joined" and I couldn't send a message because "I hadn't joined the channel". This happens sometimes, so I hit disconnect, to reconnect. Not knowing my config has been deleted. I would prefer better wording.

**Comment by YaManicKill** [comment]
Maybe it would be better keeping the config in the json, but setting a "autoconnect" to false so it doesn't reconnect, but if you do "/connect name" it'll reconnect and reset "autoconnect" to true? 

I feel like maybe this would be less confusing, and more useful.

Having said that, the whole config on the server for what irc we connect to is all a bit disconnected from the frontend. We need to have a think about a way to deal with this.

Maybe renaming to "remove" is the best idea, and we can have a "reconnect" which will disconnect and reconnect rather than removing it?

**Comment by dgw** [comment]
> Maybe it would be better keeping the config in the json, but setting a "autoconnect" to false so it doesn't reconnect, but if you do "/connect name" it'll reconnect and reset "autoconnect" to true?

That's what ZNC does, for example. Disconnecting does just that—it closes any open connection to that network and disables auto-connection until the user tells ZNC to connect to it again.

> Maybe renaming to "remove" is the best idea, and we can have a "reconnect" which will disconnect and reconnect rather than removing it?

Separating the concepts of "disconnecting" and "deleting" a network would be great. (I swear this has come up before, but if so I can't find the thread.)

**Comment by xPaw** [comment]
Fixed by #2114
