### ISSUE TITLE
Make possible to override user colors

### ISSUE THREAD

**Issue by bews** [thelounge/thelounge#1164]
Is anyone interested in this in the first place?

I tried to implement this in #1096, but it didn't work well.
My second try uses `css` to change color and looks like this:

![2017-05-12_10-22-38](https://cloud.githubusercontent.com/assets/3627488/25988845/583e8698-3702-11e7-933d-ea9834e66df4.png)
![2017-05-12_10-43-32](https://cloud.githubusercontent.com/assets/3627488/25988850/5b24ced0-3702-11e7-924c-53572574e3b6.png)

It still far from complete (and requires #1130), so I'm not sure should I spend time on this or not.

**Comment by MiniDigger** [comment]
good when two active ppl have the same color and nick length, I hate that ^^

**Comment by YaManicKill** [comment]
At first I thought "Hmmm, I'm not sure what this gives us over the custom css and being able to do that" but actually I think this would be a useful feature that would be quite complicated to do with custom css, that this might actually be quite nice.

A couple of things:

1. In terms of the form that pops up, I think we'll need to discuss how we are going to do that. It'll be a brand new UI concept for the lounge, we haven't done any modals before, so we should discuss how they should look.
2. Will this just do it for a specific username, I'm guessing you won't try to track usernames, as they would have changed colour anyway (I'd suggest not trying to track them, because that's quite complicated and will likely get the PR turned down if you do that).
3. Guessing this will save over refreshes? Will you use the options.js?

In general, I don't have anything against this feature in theory. Could very well be useful, and a nice value add. But I can't speak for other maintainers, obviously.

**Comment by bews** [comment]
> we should discuss how they should look.

In this example it uses background and animation from #1130. So the only new elements here are red button and this window itself. Anyway it's just a fast draft, so any ideas are welcome.

> Will this just do it for a specific username, I'm guessing you won't try to track usernames,

Yep.

> Guessing this will save over refreshes? Will you use the options.js?

Yes, there should be array `username => color` in options.js, which will be transformed to css.
And here I still don't have a clear plan how to do this. Rough idea is to add another css block above custom css and then try to build it with js.

**Comment by astorije** [comment]
I'm personally not a fan of this but for a different reason: while the added value is going to be really really low (I'd rather have very good default colors + have them easily overridden in themes and/or custom CSS), I sure do not want to have to maintain that.
So my user's hat says "I don't mind/care" but my developer/project maintainer's hat says "oh please no" lol.

Just my 2c obviously :)

**Comment by xPaw** [comment]
I'm closing this as it won't be implemented.

You can achieve this with CSS if you really need to.
