### ISSUE TITLE
First default nickname does not contain the random numbers prefix at the end of nickname

### ISSUE THREAD

**Issue by christer88** [thelounge/thelounge#1400]
//
                // Nick
                //
                // @type     string
                // @default  "lounge-user"
                //
                nick: "Chat_Guest_",

First default nickname does not contain the random numbers prefix at the end of nickname. This looks a bit weird when you have a user named 'Chat_Guest_' and the next one 'Chat_Guest_245' etc.

Suggest forcing the random numbers prefix on first user.

**Comment by astorije** [comment]
Hey @christer88!

So, [the way this works currently](https://github.com/thelounge/lounge/blob/master/src/plugins/irc-events/error.js#L29-L32) is that when one connects to a server, the given nick is set, and if it comes back as "already in use", gets randomized with those added integers.

At the moment, when you click on "Connect", the system doesn't know if the nick that's sent to the server is the default one (from the settings defaults) or if the user set something before pressing the button.

This means that if we were to do that, we couldn't just always append the integers to the nick, or you would never be set the nick you asked for. Alternative would be a clumsy check in the code linked above, where if nick set at connect time == default nick, then add random integers, otherwise keep the nick as is. The current rationale is that we always prefer to give the default nick if available before defaulting as a last resort.
I don't think we can do something dynamic like `"Chat_Guest_${n}` that would be convenient to use and maintain.

I understand where you're coming from though, and maybe the check mentioned above would work. I don't like the idea of not doing what a user asks for, and conditionally on top of it, users should always be in control of the data they input. I think I would rather keep it that way, as it is less confusing than the alternatives I can think of, but I am open to suggestions. @thelounge/maintainers, what do you think?

**Comment by christer88** [comment]
Closing this issue. @xPaw has been so kind to implement this with https://github.com/thelounge/thelounge/pull/2090

**Comment by astorije** [comment]
Yes, and in a very elegant and simple way on top of that!
