### ISSUE TITLE
Auto-opening user list

### ISSUE THREAD

**Issue by nomadturk** [thelounge/thelounge#178]
On mobile,

When Auto-Rotate is open and you rotate your screen user list opens itself. 
Even if you close it, the next time your screen rotates it does pop-up again.

Tested on Android, Chrome

**Comment by YaManicKill** [comment]
The bug is even more fun than that. Follow these steps for a really awkward user experience:

1. Open the lounge on mobile device
2. Rotate to landscape
3. Note that user list opens
4. Click the icon to hide the user list
5. User list hides
6. Rotate to portrait
7. User list appears again

Probably because of [this code](https://github.com/thelounge/lounge/blob/master/client/js/lounge.js#L725). We are dealing with showing/hiding the userlist in 2 different ways on different sized screens.

The button sets "rt" to the viewport class, and on <786, we use this to mean "show the user list" and on >=768 we use this to mean "hide the user list".

So, we need to sort that out, and then #51 can probably be used to solve the rest of this issue.

**Comment by xPaw** [comment]
I believe this particular issue would be fixed on master. It will still toggle depending on screen size, but it should remember whether you closed it or not on that size.

**Comment by McInkay** [comment]
Correct, just tested and it works as would be expected. Closing.
