### ISSUE TITLE
Renaming networks

### ISSUE THREAD

**Issue by nomadturk** [thelounge/thelounge#179]
It would have been good to rename an already saved network over the web client.
Especially for multi-user environments not everyone has access to the file system.

Sometimes you might want to change the network name or user name.
I think instead of deleting it, adding it again, trying to take a not of your channels etc., just like when we are adding a new network, having an option to change all these would be great.

**Comment by maxpoulin64** [comment]
Adding to that, I think overall it would be nice to have some sort of UI to edit a network:

* Network name
* Nicks
* Password
* Post-connect commands
* other settings

It might be a while before this is implemented however, I think this would need a lot of reorganization on the server to be possible.

**Comment by peperunas** [comment]
I think this issue deserves more attention. It's a pain to edit a network details.

**Comment by astorije** [comment]
@peperunas, feel free to submit a PR if you want to help speed up the process.

**Comment by xPaw** [comment]
I did half of the work for this, but have no motivation to finish it up. Feel free to pick it up: https://github.com/thelounge/lounge/compare/xpaw/edit-networks

**Comment by Haarolean** [comment]
Upvoting this

**Comment by McInkay** [comment]
@Haarolean You can upvote by leaving a 👍 on the original post, rather than leaving a comment. That's the best way to leave your feedback if you don't have anything other than "Do this please". Thanks :-)

**Comment by Haarolean** [comment]
@McInkay yeah but that totally brings more attention, considering it's open since 2016 :)
Sorry if I'm writing in the wrong PR/issue again but that's sort of complicated here, you have about five PRs/issues about almost one thing.
No idea if anyone has mentioned already that 'disconnect' and 'remove network' should be different **separated** actions. As I see https://github.com/thelounge/thelounge/pull/2114 provides only disconnect feature, I don't see the 'remove network' menu item.
