### ISSUE TITLE
Support Oauth with Google

### ISSUE THREAD

**Issue by aero31aero** [thelounge/thelounge#2065]
Hey! I really loved testing out thelounge, but the process for creating users is really tedious and they'd have to tell me their passwords for that. Also, I have to manually create users instead of having an Oauth based sign in strategy.

Is there any plan on adding Oauth? Is it a likely to be tough job?

**Comment by astorije** [comment]
Hey @aero31aero!

Adding users to The Lounge is not _that_ tedious. Users are stored as text files, so if you really need to create a lot, you can batch create the same file with a different user name.
It's not ideal, but if you have an immediate need and are not able to contribute or update the codebase to satisfy your needs, that's a valid, working alternative.

Back to the feature request now: OAuth.
As you probably noticed, we currently support the naive username/password auth (local auth), as well as LDAP. The problem with the LDAP integration as part of the main codebase is that no one in the project maintainers' run The Lounge with LDAP, and it requires additional knowledge/setup to test this as we go, so we have a history of breaking it and not noticing it for a while. It also adds a non-negligible maintenance cost, and causes all users to install LDAP dependencies, which (up until upcoming v2.7.1) also comes at a cost and has been breaking in users' setups quite a bit.

For this reason, I am opposed to add more authentication systems to the main codebase. In an ideal (hopefully short/mid-term) future, The Lounge would expose auth capabilities via an API, and systems like local auth, LDAP, OAuth, etc. would simply plug to that.

Now the hard part is to design this API so that it makes all this possible. I know very little about OAuth, if you know yourself, what mechanisms would we need to provide to make it possible?
You can look [here](https://github.com/thelounge/lounge/tree/master/src/plugins/auth) to the the """API""" we have for local/LDAP auth. It's very simple, mainly a function that takes a few things in arguments such as username and password and compares it to saved password (local) or forwards it to LDAP. In the case of LDAP, we create the user if authentication is successful and the user does not exist (we need to make this more generic and not offer the entire `ClientManager`/`Client` objects to the plugin!).

What I am trying to identify here is if all it would take for OAuth to work would be that same function call, or if there are other entry points we need to expose.

**Comment by aero31aero** [comment]
I have some experience with Oauth and I think I'll give it a go. I'll be adding passport.js as a dependency, and adding the following parameters in the config file:

```
auth: {
  google: {
            clientID: '',
            clientSecret: '',
            callbackURL: "domain.com/auth/google/callback",
            profileFields: ['emails']
  }
}
```

Also, and this is just my opinion, having auth backends together in the main project might not be a bad strategy. Off the top of my head, I can recall some projects that do this well. Example: Wiki-js's config file: https://github.com/Requarks/wiki/blob/master/config.sample.yml#L61

**Comment by aero31aero** [comment]
Just a minor update: OAuth's usual way of working with requests, and thelounge's use of sockets, is making this task a little bit tough from the keeping the code clean standpoint.

**Comment by poVoq** [comment]
Any update on this?

Nice would be also a way to authenticate against an external SQL user database on the same server from a website or forum etc.

**Comment by McInkay** [comment]
> Any update on this?

Nope. When someone picks it up they will mention.

> Nice would be also a way to authenticate against an external SQL user database on the same server from a website or forum etc.

We might add plugin support for authentication as that might be a good way to deal with all these extra authentications. We probably don't want to add them all into core.

**Comment by astorije** [comment]
> When someone picks it up they will mention.

If someone does however, note that it is rather unlikely that we would add an extra authentication method into core (we've broke LDAP so many times!), and extremely unlikely if any new authentication method relied on any non-OSS third-party.

But if someone picks it up by making authentication pluggable so we can have external packages for authentication, that would be very strongly supported :)

**Comment by xPaw** [comment]
Closing because this won't be added to core.

**Comment by SomeGeek** [comment]
And what is your opinion about dual factor authentication support?
