### ISSUE TITLE
Show that there are unreads/highlights in collapsed network

### ISSUE THREAD

**Issue by McInkay** [thelounge/thelounge#2223]
Currently, if you have a network collapsed, you can't see if there are unread messages and notifications in channels under that network. This can especially be confusing if you have a number of collapsed networks, and there's an unread highlight somewhere, meaning you have to uncollapse each network until you find where it is, if you want to clear the notification.

**Comment by astorije** [comment]
Ouch, the UI/UX on this is going to be a brain teaser.

One idea to keep things simple could be to simply sum all unread badges into the server one.

**Comment by McInkay** [comment]
Yeah, I thought about that but ... is it confusing having the badge meaning different things but in the same place, and with no clues as to which it means? I'm also not 100% the best way to do this but I think we do need to do something with it.

How about a dot with the same colour as the badge that shows if anything under the network has unread/highlight? 

Something like this? (Completely rough draft, horrible css, could be better, but just to get the idea)

![](https://files.yamanickill.com/f3VsMQf-.png)

Because knowing exactly how many unread/notifications there are isn't the key thing. The key thing is "are there", and you want it to be clear when there's something on the lobby (which you can see and select) and when there's something below it (which you can't see or select)

Does that make sense?

**Comment by astorije** [comment]
It does make sense. The problem is that, with this, server line gets a bit more cluttered: collapse/expand caret, badge for collapsed unreads, badge for server unreads, join channel icon.

The other issue I see is that it's adding another element for something somewhat similar, so now you have regular unread badge, highlight unread badge, icon for regular collapsed unreads, icon for highlight unread badge.
That's why I think it's actually simpler to just aggregate/sum everything, combine both metaphors for unreads.
It's not so much about the accurate number of unreads (I agree that this number is not as useful as for separate channels), it's more about trying to keep concepts simpler.

If you think about it, combining "stats" in things that can be condensed is a pretty common pattern, and probably why I was thinking of that in the first place: in email clients, number of unread emails is usually combined in the parent folder; in file trees, size of folders are usually the sum of all file sizes in it; application notification counters in task bars are usually sums of all notifications in said apps (this sentence is unclear lol, I mean [this](https://user-images.githubusercontent.com/113730/37505164-ae24c28a-28b9-11e8-905c-7f20166135be.png) where I might have messages from 5 different people for all I know), etc.
Of course, this is a very broad comparison not meant to be a "see, everyone is doing _this_ so I'm right", just trying to find examples of similar patterns out there to explain where I come from :)

**Comment by McInkay** [comment]
>  The problem is that, with this, server line gets a bit more cluttered

True, but most of the time the server doesn't have unread messages in it, so it'll be replacing something rather than adding to it.

> The other issue I see is that it's adding another element for something somewhat similar, so now you have regular unread badge, highlight unread badge, icon for regular collapsed unreads, icon for highlight unread badge.

This isn't necessarily a bad thing, I don't think.

> It's not so much about the accurate number of unreads (I agree that this number is not as useful as for separate channels), it's more about trying to keep concepts simpler.

In this case, maybe we should be removing the number when it's collapsed, and replacing with the dot instead?

> If you think about it, combining "stats" in things that can be condensed is a pretty common pattern, and probably why I was thinking of that in the first place: in email clients

Is it? I don't think I've seen that, actually. I don't tend to have nested email folders, so maybe I've just not come across it. Size of folders is very different because a folder by definition includes everything under it. But a server lobby doesn't include the channels beneath it.

I just think it's confusing UX wise to have 1 thing mean 2 different things depending on whether it's open or closed. I'd be totally find with removing the number on the server when it's collapsed and just showing the indicator similar to what I suggested above. We could even make it so that if you click on a server lobby when it's collapsed, it uncollapses rather than selects the lobby.

I think the problem is that the server name here is referring to 2 things. The network and the lobby. When a network is collapsed, realistically it should just refer to the whole network rather than the lobby itself, so maybe it shouldn't be clickable in that case.

I know I'm going to regret asking this but ... can someone tell me what textual does in this case? :-P

**Comment by dgw** [comment]
> I'd be totally find with removing the number on the server when it's collapsed and just showing the indicator similar to what I suggested above. We could even make it so that if you click on a server lobby when it's collapsed, it uncollapses rather than selects the lobby.

All of this sounds good to me.

> I know I'm going to regret asking this but ... can someone tell me what textual does in this case? :-P

Textual doesn't show anything from the contained channels/queries when a server is collapsed. (Did you regret that? :P)

**Comment by dgw** [comment]
>> Textual doesn't show anything from the contained channels/queries when a server is collapsed. (Did you regret that? :P)
>
> So you are saying whatever we do here, it'll be better than what Textual does? Huh, that's not normal.

It could have changed in Textual 7. I never upgraded from 6 because I didn't feel like buying it again. Everything I say about Textual is based on Textual 6 (for future reference, until stated otherwise).

**Comment by McInkay** [comment]
Shall we push this to 3.1, because it looks like we haven't agreed on the UX for this, and it'll be a lot easier to do with vue after #2636
