### ISSUE TITLE
URL parser does not include '!'

### ISSUE THREAD

**Issue by Wetrain** [thelounge/thelounge#2343]
* *Node version:* 
*unknown*
* *Browser version:* 
Epiphany (gnome browser) 
* *Device, operating system:* 
x230 Fedora 27
* *The Lounge version:* 
2.7.1
---
This URL is not parsed correctly as the exclamation point is not included in the URL:

https://en.wikipedia.org/wiki/Dig!

End up becoming 

*formatted link* https://en.wikipedia.org/wiki/Dig> *formatted link* !

However https://en.wikipedia.org/wiki/Dig%21 is parsed correctly

**Comment by McInkay** [comment]
Yeah, so it's only not included when it's at the end of a url, which is because doing something like "Go to my new site, http://www.excitingnewsite.com!" would send you to the wrong url.

We have to make a decision here as to which causes more issues, and ... frankly, we think there are going to be more cases when people are excited about their url than the url including `!` as the last character, so we will keep the current functionality.

Sorry if this is disappointing, but I hope you understand the reasoning.

**Comment by dgw** [comment]
This turned me on to an inconsistency, though. The URL parser in 2.7.1 might reject `!` at the end of a URL, but apparently it will happily include `*` for some reason.

Should this be its own issue? >.>

**Comment by Wetrain** [comment]
@McInkay Hi, i can see the reasoning, but i also do not agree that ! is not worth parsing at all, it would make more sense to have a middle ground where the ! is only parsed if it is before the .com/.co.uk etc

So hello.com! That would be parsed as it currently is, but hello.com/hi! would parse the correct the whole string after the / ?

**Comment by McInkay** [comment]
@Wetrain No, we still won't be parsing that, based on what I mentioned before.

As I said, it's only when `!` is right at the end of the url. Being part of a path rather than a tld doesn't make it any less likely to cause issues. I'm sorry if this causes you issues, but it would be relatively easy for you to fork for your own purposes.

> This turned me on to an inconsistency, though. The URL parser in 2.7.1 might reject ! at the end of a URL, but apparently it will happily include * for some reason.

@dgw That should probably be it's own issue, yeah.

**Comment by astorije** [comment]
For what it's worth, all the systems I can test this that parse URLs from text (such as GitHub's comments themselves) do what we do, so that's less of a surprise for the user.
