### ISSUE TITLE
few features to add in lounge 

### ISSUE THREAD

**Issue by tavi1985** [thelounge/thelounge#2468]
- some sort of subscription/follow on what someone said in a channel (should attract facebook users)
Suppose someone says something in the main window of a channel. With this you can anytime watch what that person wrote. The messages of everyone should apear in a private window. 
- links spread to multiple channels/queryes from what you visit on web
That already can be done as far as i know , but add a premade messages feature for every link to be distributed
- auto join channels posted on main/private
This is easy , join every channel someone mentioned on main/private window
- auto visit links posted on main/private
Same as above 
- When someone mention a location in the same time a search on internet for pictures of that place to be posted automatic
I dont know how this could be implemented 
-post message at every x chosed time
This should be easy  
- some sort of description of users (domain of interests of them , interesting things etc) in which to search what you like. Like keywords for which to search , in this way finding people with same hobbyes would be easier
- some list that groups channels by theme 
- and last should be some features for privacy : block all information to be shown in whois to others , select which user should see them , a "invisible" feature for hide channels you are in and what you have posted
That is till now, i will try to come with some other suggestions. I like free and no ads internet so that is why i like to help in this kind of software. Hope you didn't got angry on a post from a regular person which has no experience in programming

**Comment by dgw** [comment]
As a disclaimer: I am not part of The Lounge's maintainer team, and these are just my opinions—nothing official about anything I say here. :smile_cat:

----

> - some sort of description of users
> - some list that groups channels by theme

These don't sound like something an IRC client could feasibly implement even if it wanted to. The server keeps track of users and channels, and the client only knows what the server can tell it. (That said, The Lounge does have `/list`, which will pull up a list of all channels the server is willing to publicize—channels that aren't secret or hidden.)

Actually, most of this list doesn't sound to me like it fits with how IRC works… or would even be possible. With the exception of sending a message to multiple channels/queries at once—that would be relatively easy to do by supporting existing multi-target syntax for IRC's `/msg` command. (It might already be supported in 3.0, I'm still on the last stable version.)

> - some sort of subscription/follow on what someone said in a channel

I suppose making it easier to see what a particular person is saying could be a useful feature. Something like how in Textual, if you click someone's name in certain themes, it highlights all their messages so they stand out. Occasionally I used that, I guess.

> - auto join channels posted on main/private
> - auto visit links posted on main/private

Auto-joining all posted channels or auto-opening all links sounds like a really bad idea on multiple levels. Think of the drive-by infection possibilities of spamming a channel filled with The Lounge users with malware links that they would all open automatically, or what would happen when the usual channel-spam comes through on Freenode and mentions spammers' channels that users would be joined to without warning.

> - post message at every x chosed time

Posting a message at some interval is best done by a bot, not a user's client, IMO. Though the forthcoming plugin system (see #1422) will likely make it possible with a plugin, it's likely not a good core feature candidate. (Doing this in every other client I've used requires at least writing some custom script/plugin, when the client supports it, and isn't possible if it doesn't.)

> - post location/map of where you are in a window

Posting a map of your location is probably best left up to services that provide this already. There are several of those already in existence (to name a couple, Google Maps and Glympse). It's also probably not a great idea to share your precise location on IRC for safety reasons.

**Comment by tavi1985** [comment]
1 Maibe ilke searching in private windows of every user a message they deliver about themself and in that to perform the search. And the windows should be opened in background. 
2 Maibe visit links/channels posted by a user you choose should eliminate the spammers? Users should be easily selected by multiple select in the users column. First click on a "select users to visit links/channels from" menu then multiple select users
3 okay maps isn't good ideea.  Then i remind that long ago when i used irc where some nice drawings or something made from characters which everyone could paste in the channel window in some irc clients. Could you upgrade that to emoticons or something being colourful? 
4 should be a feature to block collecting of data in main/private windows by detect bots who search for data like cambrige analitica , because i suppose that that was done to facebook can be done similary to irc

**Comment by dgw** [comment]
1. I don't know where this "message they deliver about themself" is going to come from. It's not like IRC clients have a "bio" or "about yourself" field to draw from; people would have to specifically write it, and then manually send it to you. But you've got part of this already: incoming private messages already open in the background.
2. Selecting trusted users for automatically joining/following channels/links is certainly a step up. But I still don't think automatically opening links is a good idea, or a good user experience. Where do the links open? Can The Lounge control whether they open in a new window or new tab? Foreground or background? What about mobile devices? It sounds like a lot of work for very little gain, though you might be able to make a case for a "links window" that just lists all links sent in your channels that The Lounge has seen.
3. Sounds like ASCII art. I don't think The Lounge should build in big multi-line ASCII art at all. Many IRC communities see large ASCII "drawings" as spammy, and while it's kind of neat to make a picture with just text you're better off in most cases just uploading to an image host and sharing the link. (A case could be made for built-in image sharing, though. IRCCloud has it. I think one of the reasons Discord has taken off so much is because it has built-in media sharing. The Lounge could definitely offer a selection of image/file hosts to upload to automatically.)
4. IRC private messages are just that, there's no way (_assuming_ encrypted connections and a trustworthy IRC network operator) for data-mining companies to intercept that. Channel messages should be assumed to be logged somewhere, even if it's a password-protected or invite-only channel. IRC is not inherently a secure protocol—keep in mind, it's been around for 30 years. (That's also why it doesn't have any support for multimedia… network connections were so slow when the protocol was developed that it didn't make sense to even think about sharing pictures etc.)

**Comment by xPaw** [comment]
Closing as @dgw explained most of it already, and it was discussed further in IRC.

Next time please create one issue per suggestion.
