### ISSUE TITLE
Option to silence certain channels

### ISSUE THREAD

**Issue by kuba-orlik** [thelounge/thelounge#2490]
As a user, I think it would be very neat to make some channels trigger notifications for all messages, and some be always "silent" :)

**Comment by McInkay** [comment]
Few questions regarding what you would expect:

1. If you silence a channel, you would clearly expect no notifications at all, if I understand correctly?
2. Would you expect no unread marker as well? So it would show as always being read?
3. Would you expect it to look different in the sidebar at all?

**Comment by kuba-orlik** [comment]
1. Yes
2. I think unread marker would be nice
3. I think a simple indicator on what channels are silenced and which aren't would be nice

I also wonder which semantic to choose: 

* silencing a channel - the default is to notify, unless silenced
* marking a channel as "favourite" - it is displayed with a star/heart icon in the sidebar, and gives notifications for each message

**Comment by astorije** [comment]
This is my silly contribution: rather than "Silence", I would call this "Mute" :)

I agree with @kuba-orlik that it would be nice to keep unread marker.

Re: sidebar, I would dim the channel (reduced opacity). I would also replace the icon with something like 🔇, but sadly there is no such thing in free FA for now, just https://fontawesome.com/icons/microphone-slash?style=solid and https://fontawesome.com/icons/volume-off?style=solid. We could use the former and request a slashed volume off? (There is one in Pro, but it's slightly different) They tend to add a bunch of icons with new versions these days, so we can hope.
Maybe move the muted channel at the bottom of their network? Kinda awkward with the current sorting ability.

Re: favorite, I wouldn't worry about this for now (and definitely not for this issue). I think there is another issue somewhere where I suggest the ability to "Star" a channel which would move it to the top. I think always-on notifications should be separate from the ability to star.

**Comment by kuba-orlik** [comment]
Re: favorite, I think the default should be no notifications, and only receiving notifications for some specified channels. I think that "Favourite" semantics are better suited here, because I suspect there usually are only a few channels that we'd like to be notified for, and many more channels that we are passively watching. Muting every new channel would get tiresome

**Comment by astorije** [comment]
I'm not sure if I'm following and I'm wondering if we're not misunderstanding each other.
Are you suggesting to change the current behavior (desktop/push notifications when being mentioned only) to a muted-by-default (no notifications at all, even when mentioned) and that only "favorite channels" have notifications (only when mentioned)?
Or are you saying that favorite channels must send desktop/push notifications with all messages, and non-favorite channels must keep the current behavior?

Regardless, I think this is side-tracking a little bit the initial feature request, where "muted channels" don't emit any kind of notifications and appear as muted (dimmed) in the channel list. But depending on the answer to the questions above, I could see why you brought this up, and that would justify agreeing on an answer on this overall.

**Comment by kuba-orlik** [comment]
I think that the perfect solution for me would be that by default channels notify me only when I'm mentioned, but when I "favourite" a channel, I get notifications for all messages

**Comment by McInkay** [comment]
> but when I "favourite" a channel, I get notifications for all messages

If we implement favouriting channels, that seems like a really weird thing to tie to it. We have the setting for getting notifications for all messages, so when we implement network and channel settings it'll have that. But favouriting shouldn't mean automatically notifying you for everything imo.

**Comment by astorije** [comment]
@kuba-orlik thanks for clarifying. Then in this case this is definitely beyond the scope of "muting" a channel so we might want to stick to this in this current issue.
