### ISSUE TITLE
Better formatted logging.

### ISSUE THREAD

**Issue by TheDetectiveTaco** [thelounge/thelounge#2499]
I am going to come right out about this, the logging format is really crappy. Logs like this would be easier to read, and just look better. http://echelog.com/logs/browse/supybot/1311285600 Hope something like this can happen in the future.

**Comment by Jay2k1** [comment]
Hmm, as I see it, the differences aren't that big. What I have noticed:
TL uses date&time for the timestamp, yours only uses the time, because currently TL has only one log per channel with the complete history in it.

I think it would be a good idea to change it so that it writes individual log files per day, i.e. by adding a subfolder for each channel and then have `YYYY-MM-DD.log` logs in there.

Apart from that, events could use a little tweaking which shouldn't be too hard... currently they look somewhat weird:
```
[2018-06-02 13:43:33] * creesch (~creesch@unaffiliated/creesch) quit Ping timeout: 256 seconds
[2018-06-02 13:43:52] * creesch (~creesch@unaffiliated/creesch) join
[2018-06-01 16:26:22] * Q mode +o Jay2k1
[2018-05-29 11:47:11] * Jay2k1 kick test
```
Kicks don't log the target at all, just the person kicking and the reason (test in this example).

**Comment by xPaw** [comment]
Text logs haven't really been touched. If you want to be parsing logs, you can just query the sqlite version which comes in 3.0.
