### ISSUE TITLE
Opera on iOS - issues with text box moving upwards

### ISSUE THREAD

**Issue by fnutt** [thelounge/thelounge#2522]
There's an issue when opening Opera browser and when you click on the text box where you type messages. When you click on the box it moves it upwards. Same happens when you press enter to publish the message - the box moves down. I've tried with both Mininapse and default theme.

https://www.dropbox.com/s/g4l6jgcclgdjev5/2018-06-04%2013.45.39.mp4

iOS 11.3 on Apple iPhone 8 Plus
Opera 16.0.10
TheLounge 3.0.0-pre.6

No issue with Safari.

**Comment by astorije** [comment]
FWIW on Safari, latest iOS, iPhone 8 **non-Plus** (because I know it does _not_ happen on the iPhone X for example), I am having a similar though "reverse" issue: when the virtual keyboard opens, the input shifts right under:

<img src="https://user-images.githubusercontent.com/113730/41138231-d6989a30-6aad-11e8-826c-d6573e00ed66.png" width=200> <img src="https://user-images.githubusercontent.com/113730/41138232-d6a67bdc-6aad-11e8-97eb-62140f7adb3f.png" width=200>

Super annoying, but I have had this since I moved to iOS end of last year, so who knows when that started to happen (and I'm not entirely convinced the root cause with your issue is the same).

Same as your other issue, could you try older versions to see if it happens there as well?

**Comment by christer88** [comment]
This happen in 2.7.1 as well. It has been super annoying for a long time.

**Comment by xPaw** [comment]
This is most likely related to Safari itself (since Opera has to use it under the hood too) and I'm not sure there's anything we can do about it.

https://stackoverflow.com/a/40572589/2200891

**Comment by astorije** [comment]
Agreed re: most likely a Safari bug. Urgh.

Do we want to try this? https://gist.github.com/Linrstudio/7236158c6c8d8103b9fb#1-use-shrink-to-fit-meta-tag
It's a long shot, but 🤷‍♂️

We might get lucky with iOS 11.4 though: https://bugs.webkit.org/show_bug.cgi?id=170595
Updating my iPhone right now...

**Comment by astorije** [comment]
> We might get lucky with iOS 11.4 though: bugs.webkit.org/show_bug.cgi?id=170595
> Updating my iPhone right now...

Well, no dice for me...

**Comment by fnutt** [comment]
https://www.opera.com/no/mobile/touch seems to not have this issue. I dunno why.
