### ISSUE TITLE
Auto-detected URLs shouldn't assume https

### ISSUE THREAD

**Issue by benharri** [thelounge/thelounge#2525]
* *Node version:* v9.11.1
* *Browser version:* chrome latest
* *Device, operating system:* windows 10
* *The Lounge version:* source@de1e609

URLs without a scheme are now detected by linkify-it.js since #2397 was merged.

It's the server's responsibility to redirect from http->https, not the client's. This breaks many sites that do not have SSL certs where I would expect a link in thelounge would work, but instead results in a nasty `ERR_CERT_AUTHORITY_INVALID` error in the browser.

**Comment by Jay2k1** [comment]
We already concluded in #406 that 
- https is still not the default 
- if you enter a URL into a browser without a protocol, it uses http
- it's the webmaster's job to forward to https

**Comment by astorije** [comment]
Hi @benharri!

There was some extensive discussion at https://github.com/thelounge/thelounge/pull/2397#discussion_r185695728 about this. Conclusion was that URLs provided without a scheme would be secure-by-default. If the link _has_ to be http, then it should be shared with `http://`. This follows the current trend of pushing for security/privacy (yes, posting an HTTP link has security implications even if it redirects).

HTTPS is not the default on browsers because user base is literally everyone, and entering a URL is one of its main job, while expanding URLs is a convenience feature for us (and expanding URLs without a scheme or `www.` was not even supported before). However, the browsers' move to mark any non HTTPS URL as insecure is in the same vein.

Hope that clarifies :)

**Comment by Jay2k1** [comment]
> while expanding URLs is a convenience feature for us

It's not (only) about expanding URLs, it's mainly about making the posted URL clickable and by adding https, actively altering it in a way that potentially breaks it. Not only is this very bad UX in my opinion, it is also _confusing_ because users might go "your link doesn't work for me" and get "it works fine here" and wonder why they see ECONNREFUSED or a certificate mismatch error.

> However, the browsers' move to mark any non HTTPS URL as insecure is in the same vein.

While the idea of pushing towards more security/privacy is understandable and good, a red lock in the URL bar with an otherwise fine working website is a different experience than getting ECONNREFUSED.

**Comment by xPaw** [comment]
I have already stated my reasons in favour of `http` in the PR. TL;DR: Defaulting https creates a negative user experience and is not related to security.

@McInkay what's your take?

**Comment by benharri** [comment]
If autodetecting URLs in thelounge actively breaks them, I'd rather disable protocol-less detection than assume something we can't know about every link.

**Comment by Jay2k1** [comment]
I'd still consider that a bug, because it used to work fine and this would not only break sites that don't work with https, it would break all sites (posted without protocol).

**Comment by McInkay** [comment]
Oh no, I was hoping I might get away with not giving my opinion on this and that everyone would come to an agreement.

So.

It's a tricky one.

I would say that I agree that it would be good if we could default to https, and actually the majority of sites should still work.

However.

I don't think there are many sites out there that have https and don't forward http to it. It's becoming common (and best) practice to make your server do that. However, literally no one forwards https to http when they don't support it. They just don't support https. Therefore, you are way more likely to have something broken by pointing to https, and the small issue with http is that there may be some sites that enable https but don't forward http to it, meaning you end up on http. However, browsers are starting to help with this by making it clear when you are on http and shouldn't be, so....

I'd say go with http, despite the fact that in general I would disagree with that.

**Comment by astorije** [comment]
Alright, it looks like everyone agrees on defaulting to HTTP for protocol-less URLs. I'm with @McInkay, I really wish we didn't have to do that, but all the arguments stated above and in that other PRs make sense and I buy that the benefits of one side outweigh the drawbacks of the other side.
Hopefully in a year or 2, the story will be different!

Re-opening the issue, whoever wants an easy PR, have at it! :)

**Comment by SinZ163** [comment]
What about having an advanced options checkbox to enforce https or not on links

**Comment by dgw** [comment]
Even I think this is too trivial for a setting, and I love checkboxes… 😝
