### ISSUE TITLE
Style "Currently active" in session list to stand out

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#2562]
Just now I was looking at the session list on my phone, and it's actually hard to see it at a glance, because it's stylistically the same as "Last active ..."

**Comment by astorije** [comment]
Instead of styling "Currently active", what do you think of separating active sessions in a dedicated category as such:

<img width="300" alt="screen shot 2018-06-16 at 00 45 22" src="https://user-images.githubusercontent.com/113730/41495837-decb0132-70fe-11e8-85f6-50d2ce4e86fa.png"> <img width="300" alt="screen shot 2018-06-16 at 00 47 05" src="https://user-images.githubusercontent.com/113730/41495838-ded93d1a-70fe-11e8-856b-32103f520bf7.png">

And if you like it, which version do you prefer? (constant spacing between buttons or constant spacing between texts)

**Comment by xPaw** [comment]
Yeah I was thinking to do the same. You decide which one looks better spacing wise.

**Comment by astorije** [comment]
The alternative I can think of is something like this:

<img width="476" alt="screen shot 2018-06-16 at 18 50 57" src="https://user-images.githubusercontent.com/113730/41503017-4f3327d2-7196-11e8-93dc-5060bae93202.png">

I feel like I prefer this, but I could be convinced otherwise. Thoughts? (It doesn't have to be _that_ color specifically of course)

**Comment by xPaw** [comment]
If we were to style 'Currently active' under the IP, I think it should look like a badge (different background, etc).

**Comment by astorije** [comment]
Interesting idea. Something like this?

<img width="484" alt="screen shot 2018-06-17 at 20 05 41" src="https://user-images.githubusercontent.com/113730/41513418-ef052d04-7269-11e8-9514-3b545a4c49bf.png">

I'm not a huge huge fan but I don't mind too much either way.
For one thing, I'm toying with something else that uses the same sort of badge, and it would be kinda nice to have the same one actually.

**Comment by astorije** [comment]
btw I tried with plain background and it's just too much on white background.

**Comment by dgw** [comment]
How about badging to the right of either IP or the browser type? Might look less visually busy.

Maybe include "Last used" or "Last activity" (or "Last seen"?) always, and then make "Currently active" a badge-only thing.

**Comment by astorije** [comment]
The idea is that if the connection is currently active, the "Last used" timestamp will (or at least should) always be the same as the current time, so that's not very useful.
If we add a badge + keep the "Last used", then it would be more visually cluttered, actually.

In terms of positioning, if badge or styled string, I would suggest keeping it where it is for 2 reasons: this is where there time-related (now vs. given date) is located, so I think it makes more sense at an information architecture level; on a more technical note, if user agent happens to be very long for some reason, then the chances of overflowing to the next line increase (it wouldn't as much on the IP line, but I think it would be weird to collocate that info).

Of course, maybe I'm not having a fresh enough look at this and there might be a better way to do that by re-thinking this section, but if there is I'm just not seeing it yet :D

**Comment by xPaw** [comment]
@astorije That also looks fine.

**Comment by christer88** [comment]
I think I prefer https://user-images.githubusercontent.com/113730/41495838-ded93d1a-70fe-11e8-856b-32103f520bf7.png out of the ones shown above. I do support the idea of showing the current session better, and to also show which sessions are active other places.
