### ISSUE TITLE
Prefetched generic URL previews are unhelpful and ugly

### ISSUE THREAD

**Issue by andyross** [thelounge/thelounge#2583]
I just discovered prefetch, which I love (why is it not default?).

Nonetheless, if someone pastes an URL that points to a site that the engine doesn't recognize and can't parse (I don't pretend to know exactly what its heuristics are), it does nothing but put up the HTML title in a big bold block with outlining.  That's... not really helping anyone, and takes up a bunch of chat space.

I'd suggest fixing the logic so that a site needs, I dunno, two of "title", "thumbnail" and "summary" before it's shown by default, otherwise it starts collapsed.

**Comment by astorije** [comment]
> (why is it not default?)

A long, long time ago, when switching from Shout to The Lounge, we had a security issue with prefetch and decided to disable it by default. A few other arguments helped make the decision (lack of caching, potential abuse on public mode which was the default mode, etc).
We're at a point where prefetch is good and has been worked on a lot, so I think it could be enabled by default, especially since The Lounge ships now in private by default. @xPaw, did you have other concerns about this? I think v3 could be a good place to do that, what do you think?

> it does nothing but put up the HTML title in a big bold block with outlining. That's... not really helping anyone, and takes up a bunch of chat space.

This logic is intentional. It might not help your own use cases, but displaying the page title is already some amount of preview. If a better title is available, it will be used, and if a description and/or thumbnail is available, it will be used.

Do you have any particular URL on hand that you could share so we can test the outcome?

In the meantime, I will close this issue since the feature works as intended.

**Comment by dgw** [comment]
I disabled automatic link expansion because it's not usually helpful in my chats. But that's not a problem with the feature. People posting links that don't need title expansion isn't The Lounge's fault.

**Comment by astorije** [comment]
> It's just ugly.

This is not very helpful.
In general (and this is why we have the issue template that you did not include), we are in a more actionable situation if you provide things such as which version of The Lounge are you using (like I said, prefetch has changed a lot recently), actual examples of what you are describing (in this case, URLs that you find TL shows ugly), screenshots (in this case, maybe what Discord "gets right" or what TL gets wrong), etc.

> when someone types "www.whoever.com" they don't mean for readers to navigate to the page. Yet we still see a big blob of "preview" of a site that probably doesn't have much on it at all. [...] If it's a real URL, sure.

I don't know if you meant this as an actual example or not (again, we can't guess what feels wrong), but "www.whoever.com" does not generate a preview. We also can't know what users meant or didn't mean, if they posted "a real URL" or not. Feel free to provide comparisons with results on Discord, but I don't see how they can get this right just yet.

> But an URL without a path, or a protocol prefix, or a thumbnail.... come on. I know that's "as intended", but it's really not a good user experience.

A website without a thumbnail is a perfectly valid website. In fact, my own website only has a title, no thumbnail or description, it doesn't mean it's not a "real URL".
Again, what would be a better user experience to you? Answer cannot be simply to not display the preview, as this would just hide the problem (if any) rather than fixing it.
