### ISSUE TITLE
Add an option to display 12hour times

### ISSUE THREAD

**Issue by nemchik** [thelounge/thelounge#2770]
It would be awesome if there were an option in the UI itself (or just config.js) to set the Timestamp format used in the UI. Currently it seems to be 24 hour time with hours, minutes, and optionally seconds. having control over the full format would be nice. This could remove the need for the "show seconds" option because that would be controlled in the Timestamp format.

**Comment by fnutt** [comment]
https://github.com/thelounge/thelounge/pull/1216 tried to deal with this earlier, but was closed.

I can understand why some would want this in TheLounge, since they are used to read 12-hours am/pm formatted time. I think TheLounge should provide an option for each user to choose either 24-hours or 12-hours AM/PM. I'm however against adding full time/date-format editing, since this is rather cryptic for most users.

**Comment by MiniDigger** [comment]
could add a 12/24 format switch as normal option and a full date format editor as an advanced option 
* runs *

**Comment by astorije** [comment]
Yep, so far we agreed to add a 12/24h option on top of the "show seconds" one. That should cover 99% cases without having to maintain (and ask users to learn) a dedicated syntax.

Having both is definitely not something I'm looking forward to have to maintain.

**Comment by vvug** [comment]
What about the timezone? TheLounge is showing all the timestamp in UTC, even if the server it's running on is setup with a non-UTC timezone. I think the user should be able to select the timestamp TZ.

**Comment by xPaw** [comment]
Lounge formats the time in the browsers local timezone. If you see UTC, that most likely means you use Firefox with the resist fingerprinting option which breaks the timezone.

**Comment by vvug** [comment]
Now I feel... fingerprinted! That was it.
