### ISSUE TITLE
Jump Scrollback Issue - Jerky UI

### ISSUE THREAD

**Issue by thehaxxa** [thelounge/thelounge#2969]
I have witnessed a very frustrating bug where the screen will jump back and scroll back at random on messages.

Witnessed on a Dell XPS 13 running Windows 10, watch the video for context. 

https://www.youtube.com/watch?v=Ra0fFpF1S6w

Node version: v11.6.0
Browser version: Chrome 71
Device, operating system: Windows 10
The Lounge version: v3.0.0-rc.4

**Comment by xPaw** [comment]
Is that you scrolling up when it jumps? It's hard to tell what happens there, but that looks really weird.

Can you test the Vue branch? It changes the scroll handling logic.

**Comment by thehaxxa** [comment]
No its happening at random (not caused by scrolling manually). Generally it  jumps back 50% of scrollback messages. 

The Vue branch seems to have fixed it, but unfortunately it introduces a new bug for me where it gets stuck in an authentication loop when running as Chrome App i.e. (custom chrome app). Cleared Cache and setup new user but no dice. So for now I will deal with it.

**Comment by xPaw** [comment]
@Jay2k1 appears to be having the same issue on Vivaldi, the issue appears to be that it scrolls up when hovering on the user list.

I looked at a performance trace from Jay2k1 and it doesn't really run any code that would cause this (or any relevant code at all), so I have no idea why this happens.

If this issue is somehow caused by the jquery code (mouseover on user list) then Vue branch shouldn't have the same bug (you already said it doesn't).

Really no idea what's happening here, all of the relevant code hasn't changed in months.

**Comment by Jay2k1** [comment]
Correct. Here's a video: https://youtu.be/Vc78refTeyA

Unfortunately it's very hard to reproduce, I couldn't find a way so far.

**Comment by xPaw** [comment]
@thehaxxa How did you install rc4?

**Comment by xPaw** [comment]
So I believe I figured the bug out on our side, but I still believe this to be a Chromium bug.

The repro goes like this:
1. Set the window width to ~1000px
2. Scroll up in the chat
3. Move your mouse to an user in the user list

When the mouse enters the user list and sets the `active` class on the user, Chrome triggers a `scroll` event for some odd reason. This happens only once after scrolling in the chat list, so removing-adding active class doesn't trigger it all the time.

So my guess is that setting flex properties from `.window.active` triggers a layout recalculation which ends up triggering a scroll event or something.
