### ISSUE TITLE
File uploader should remove EXIF data from images (especially location data)

### ISSUE THREAD

**Issue by stalonium** [thelounge/thelounge#3025]
The file uploader is working nicely. On mobile it even gives the option to capture a picture and upload it directly. Unfortunately, unlike with image hosts like imgur, the EXIF location data is not removed from uploaded images, which can lead to unsuspecting and unknowing users accidentally revealing their location.

It would be nice if the automatic removal of EXIF data from images when uploading would be an option (which should also be the default behavior in my opinion).

**Comment by stall0ne1337** [comment]
> Sounds like a good idea. I woudn't mind looking at this at some point if I have time (while waiting for that irc-fw release).
> 
> EDIT:
> I did a quick check to see what image formats support EXIF and it seems that only JPEG and TIFF use it. Does anyone have some more info about EXIF or any other type of metadata that should be removed from uploads?

JPEG definitely seems to be the biggest culprit here since that's what's created by most cameras that embed location data. [PNG appears to have some embedded metadata going](https://stackoverflow.com/questions/9542359/does-png-contain-exif-data-like-jpg) on but I don't know how relevant that is. 

Thanks for looking into this!

**Comment by richrd** [comment]
Thanks for assigning xPaw. This will be a breeze to do after our upload overhaul :)

**Comment by MiniDigger** [comment]
pic uploaded with master (4.0):
http://metapicz.com/#landing?imgsrc=https%3A%2F%2Firc.minidigger.me%2Fuploads%2Fe22eb41f6f7bbf7c%2FIMG_20191231_235758.jpg
(https://i.imgur.com/etYtvKF.png)
pic uploaded with discord:
http://metapicz.com/#landing?imgsrc=https%3A%2F%2Fcdn.discordapp.com%2Fattachments%2F183155267402334209%2F662240533678391327%2FIMG_20191231_235758.jpg
(https://i.imgur.com/fIQTFbK.png)
pic uploaded with #3661 doesnt get detected as picture anymore, thelounge downloads it as raw bytestream and doesnt show preview:
https://irc.minidigger.me/uploads/c14468efa1896228/IMG_20191231_235758%20(1).jpg
(https://i.imgur.com/d91w8S4.png)

**Comment by xPaw** [comment]
I tried stripping exif using exif-be-gone, but it seems to be buggy, and also strips orientation. It also operates on *all* uploaded files, not just images.

I think it should be implemented in the following way on the client side in `upload.js`. In there, we already have a function to process each file one by one, and we can add some pre processing in there.

- Detect an actual image (file has a type we can check)
- Render out the image (canvas probably) with the correct orientation
- Take out the rendered image and turn it back into the `File` object so it can be uploaded

This way, all metadata should be stripped, and the image should remain in the correct orientation without having exif (since the rendered image will actually be rotated).

Thoughts?
