### ISSUE TITLE
better RTL support

### ISSUE THREAD

**Issue by LionOpeter** [thelounge/thelounge#3344]
Please improve RTL support as follows:
All user's messages should be aligned to the right
When writing text in the input box it also should be aligned to the right

**Comment by NeatNit** [comment]
As discussed on IRC: this wasn't actually fixed by #3345.

#3345 deals with displaying bidirectional text correctly - i.e. correctly render RTL messages in a LTR client.
This issue is about making the entire client RTL.

I did a *very short* experiments using dev tools. The following is a good start:
1. Add `dir="ltr"` to the main `<html>` element.
2. This CSS: https://github.com/thelounge/thelounge/blob/064d36a6cc00db8b0090343fe5eb509be7619a5a/client/css/style.css#L1295
should be changed to `right` for a RTL client. Alternatively, it can be changed to `match-parent` - though this value is still experimental.
3. Some UI elements (e.g. sidebars elements like channels and servers) need more `dir="auto"` on them.
4. Some CSS needs tweaking.

All in all, I don't think much more than that would need to be changed.
