### ISSUE TITLE
[Feature request] Option to filter out debug.raw messages

### ISSUE THREAD

**Issue by Mikaela** [thelounge/thelounge#3673]
## Feature Description

I originally enabled `debug.raw` for troubleshooting, but I seem to have a need of keeping it enabled all the time as The Lounge or IRC-Framework is hiding information I need often, such as `MODE +R` (channel reop list on IRCnet) and `VERSION` (ISUPPORT).

I like how `debug.raw` accidentally gives overview across all channels, but I would like to filter out or not have PING and PONG events logged as those are the most of traffic and I think they wouldn't usually be that helpful to see even for debugging.

**Comment by richrd** [comment]
I don't think we want to add any exceptions to the messages that are shown due to `debug.raw`. After all the point is to show everything for whatever debugging purposes a user might have. I understand your use case but it's not what the setting is intended for. I checked if it's possible to hide pingpongs with custom CSS but it seems like that's not possible either.

**Comment by Mikaela** [comment]
I have heard that there is another client doing that called `ircdog` and that has an argument `--hide=ping,pong`, so The Lounge wouldn't be the first client with that capability, but I understand your point.

I guess that even if it was possible to hide pingpongs with custom CSS, `Alt`+`a` would still keep opening the server tabs which is what mainly makes me notice them.

**Comment by xPaw** [comment]
What @richrd said is correct. I quickly looked at it before, and it's not trivial to filter them because we would have to fully parse the IRC message again, because tags come before the message type.
