### ISSUE TITLE
Support cp1251 encoding

### ISSUE THREAD

**Issue by Arkadietz** [thelounge/thelounge#371]
Hello, 

It will be possible client to support cp1251? Will be nice if there is an option in conf where you can set whatever encoding you want.

**Comment by maxpoulin64** [comment]
Setting an option in the conf wouldn't work very well, as that would force that encoding to every networks on the entire server. I would probably need to be set per-server along with the other options. In order to support this we will need:

* An additional setting in the connection page
* Make sure said setting is persisted to the network config
* Probably offer a drop-down menu to select from the supported encodings.

Good news is, irc-framework uses iconv so it should be just a matter of passing the variable to it.

I'm surprised there's still networks out there not using UTF-8 in 2016. Most clients/software in general have long gotten rid of encoding options in favor of the universal UTF-8.

**Comment by dgw** [comment]
Would it be too far out of scope for The Lounge to try to auto-detect the text encoding for each network? @astorije I know you, especially, love to go for ease of use and minimal configuration whenever possible.

> Most clients/software in general have long gotten rid of encoding options in favor of the universal UTF-8.

Don't forget about clients that pretend to support UTF-8 but mangle it, or only support it with specific fonts, etc. 😉

**Comment by maxpoulin64** [comment]
@dgw: The problem with trying to autodetect the encoding is that it tends to fail a lot and be very unpredictable. I think the server doesn't bother at all, so you will very likely end up with both encodings in the same channel.

I think the best solution would probably be to try to do the same as ZNC (which can be used as a temporary workaround until this is fixed), and try parsing as both the user-specified encoding and UTF-8.

The only problem I see with that is that there will be people needlessly using a non-UTF-8 encodings just for the sake of it "because I speak language X" and then wonder why it's always broken (and thus said encoding just won't ever die).

**Comment by apihlaja** [comment]
> I'm surprised there's still networks out there not using UTF-8 in 2016. Most clients/software in general have long gotten rid of encoding options in favor of the universal UTF-8.

It's not network setting, it's per channel thing. After testing lounge first time yesterday, I was surprised how many people are not using UTF-8. Considering that no one is complaining on channels, I'd say most of IRC clients use some kind of double encoding solution. That's what my old client (irssi) did: by default, it uses UTF-8 but you can spesify one fallback encoding.

I guess one app level fallback encoding would be sufficient solution for 99.9 % use cases.

**Comment by DanielOaks** [comment]
Generally, if you want to do more than just utf-8 you'll try decoding with utf-8 first, and then if that doesn't work then try decoding with something else like cp1251.

The 'receiving text' section on this page right down the bottom of [this page](http://xchat.org/encoding/) describes what xchat does/did, basically as described above. Receiving stuff in this sort of way can be useful and has been happening for a while in clients.

Allowing people to change the encoding they send messages with can be a bit iffy though, take that whichever way you want but imo everyone should be sending utf-8 and encouraging it wherever possible.

**Comment by maxpoulin64** [comment]
Yeah.... irc-framework isn't quite designed for that at all. It's network-wide or nothing. Maybe plugins will be able to do something with that in the future...

**Comment by apihlaja** [comment]
@maxpoulin64, not quite right, clearly intention is to add it: https://www.npmjs.com/package/irc-framework#aims

I guess I'll look into it at some point.

**Comment by astorije** [comment]
What are we planning to do with this short-term? I'm not sure there is anything we can do right now, isn't it more in `irc-framework`'s corner?

**Comment by gfriloux** [comment]
Hello, many IRC clients supports to set encoding per-chan.
This means it expects to read AND write to this encoding.
And this is actually used by some users.

I can name you at least one channel that enforces the use of ISO-8859-15 to all its users as this is the most common encoding (supported by EVERY OS, and some OSes does not support UTF-8 fully). This is a long time rule that is still maitained for the few netbsd users out there.

this can be done with irssi : 
> /recode add #chan ISO8859-15
> /recode add nick UTF-8

**Comment by xPaw** [comment]
> some OSes does not support UTF-8 fully

Serious question, how old does an OS have to be to not support UTF-8?

**Comment by gfriloux** [comment]
For example : https://wiki.netbsd.org/unicode/
and you're not immune to some IRC user using an IRC client on his Nintendo DS for fun.

**Comment by maxpoulin64** [comment]
If some people want to live in the past or with shitty IRC clients, I think it is their problem and not everyone else's responsibility to bend backwards to accommodate them. This is pretty much telling us to fix an issue because the other side of it refuses to fix *their* client to be compatible with the majority of people. There's no reason for an IRC client on a Nintendo DS to not support UTF-8. There's no reason for anything to not support UTF-8 in 2017, period. Encodings like ISO-8859-15 are fundamentally broken and incomplete.

In fact, now that we have emoji support built-in, it makes even less sense because we'd need to disable that for any encoding other than UTF-8 because they only exist in unicode. Which will also need to be documented and explained over and over. Lounge is a web client, and the web is universal, speaks many languages, and extensively uses UTF-8.

**Comment by gfriloux** [comment]
Your comments are pretty rude.
Not going to play this game.

**Comment by astorije** [comment]
> In fact, now that we have emoji support built-in, it makes even less sense because we'd need to disable that for any encoding other than UTF-8 because they only exist in unicode.

That is a very valid point, I think. In general, The Lounge tends to look forward and thinking UTF-8 only is a good think, IMO, just like we are serving with HTTP/2 automatically when we can (though not the same consequences, I know, I know).

@maxpoulin64, do I take it you think we should not do this entirely?
@xPaw, @maxpoulin64, what do you think would be the repercussions in terms of audience? Are we closing ourselves to, like, entire cultures not chatting in latin characters, or just peculiar situations like that Nintendo DS example?

If the former, then it's an issue, but if the latter, then indeed solutions should not depend on us.
Put it otherwise, and using that example above, I do not really care if you are using an outdated client on a questionable setup (Nintendo DS or esoteric OSes that do not respect modern practices). However, if the issue means people with disabilities, using screen readers or else, are affected, and there is no alternatives for them (there is an alternative for an outdated OS...), then we should look into it.

I'll let someone else in @thelounge/maintainers decide if we should close this or not.

> Your comment is pretty rude.
> Not going to play this game.

@maxpoulin64's comment was not rude. Maybe too direct or too sarcastic, but there is nothing to be offended about or take personally. And "not going to play this game" did not help 😉

If I may share some advice though: your original message could have been worded in a better way. As it is, it came across as a needy request without really bringing anything to the discussion. The Lounge, like many projects out there, is made with ❤️ on our free time, usually after work, taking over other passions or sometimes family time to help others. This means we simply do not take orders :)
The best thing you can do if you think something MUST be done is to take it upon yourself: discuss ideas, options, and consequences with others either here or on the channel, and open a PR for it. If you don't want to or cannot do that, then you must be patient and understanding :)

And because we never say it enough: To everyone in our community, thanks a bunch for all your help, support, and patience 🙏 💌

**Comment by gfriloux** [comment]
>>In fact, now that we have emoji support built-in, it makes even less sense because we'd need to disable > that for any encoding other than UTF-8 because they only exist in unicode.

> That is a very valid point, I think. In general, The Lounge tends to look forward and thinking UTF-8 only is a good think, IMO, just like we are serving with HTTP/2 automatically when we can (though not the same consequences, I know, I know).

UTF-8 Already has a lot of chars (thousands) that does not exists on ISO-8859-15.
Emoji support by itself doesnt looks like an argument.
This doesnt mean im against a will to only support UTF-8.

If you take a more precise look at my first comment, i just added the information that encoding would need to be forced per user/chan, as previous proposals were to set it per server, which would not solve anyone's case in my experience.
I said this only to help avoiding seeing efforts put the wrong way -> If it has to be done, do it properlly.

Now, i do realise that my comment may look authoritative to another POV, while my only desire was to ONLY be informative (and not take part to wether or not it should be done, or put any judgement on the quality of softwares/OS/people).

**Comment by richrd** [comment]
As this is over 3 years old and was last discussed 2 years ago I'm closing this. We can still follow what happens with kiwiirc/irc-framework#7

**Comment by xPaw** [comment]
Also see https://github.com/ircv3/ircv3-ideas/issues/38
