### ISSUE TITLE
Messages are auto pruned periodically, regardless of collapse settings

### ISSUE THREAD

**Issue by kode54** [thelounge/thelounge#3726]
- _Node version:_ v12.14.1
- _Browser version:_ Firefox 72.0.2
- _Device, operating system:_ Desktop, Arch Linux
- _The Lounge version:_  v4.0.0-80-gd7513b43

---

Basically, I have observed that the client performs an auto prune of local channel contents to only a fixed number of events, whenever the channels are scrolled to the latest message, and whenever a new message comes in under the previous condition.

Unfortunately, there seems to be a bug with how this works when join/part/quit/nick-change events are collapsed, as per the default setting. When a large number of collapsed events are near the bottom of the buffer, they count toward the prune, and result in the buffer being pruned to a few lines, and new data being fetched again to fill the screen. This clear and refetch happens every time a new message comes in, until the large block(s) of collapsed messages eventually flow offscreen.

A workaround for this should be, possibly only if collapsing is enabled, to have the pruning function either ignore the collapsed message types for simplicity, or only count successive blocks of collapsed messages as a single event.

**Comment by dgw** [comment]
#3603 seems related to this, since before that patch you would have to click a button to load more than the 100 most recent messages, regardless of if they were "real" messages or status messages (joins/parts/quits/modes/etc.). Now if the set of pruned messages doesn't contain enough "real" ones, the client fetches more. I bet there's an easy way to fix this by adjusting how pruning works to ignore condensed status messages too.

**Comment by xPaw** [comment]
This isn't a new bug. #3603 made it load more messages sure, but the pruning behaviour stayed the same.
