### ISSUE TITLE
All Different Users Have Same IP

### ISSUE THREAD

**Issue by Beyazatli** [thelounge/thelounge#3812]
- _Node version:_10.19.0
- _Browser version:_ Chrome 80.0.xx
- _Device, operating system:_ Centos 6.9
- _The Lounge version:_ 4.1.0

Hello, Im using thelounge.
I am facing a server-side error.
Whenever a user connects to the server, it is IP address of my server.
I get too many connection errors from own my irc server.
I want is to get the client (thelounge) ip address.

**In short, all users have different computers but the same ip address seems.**
---

**Comment by dgw** [comment]
Increase session limit for your TL server in the IRCd or use webirc.

**Comment by Beyazatli** [comment]
Ok. Solved.

**Comment by mascalzone** [comment]
come hai risolto?

**Comment by surewood** [comment]
> I would like to know how you solved this problem. I can't seem to get webirc to work. I set in my unrealircd.conf 4.2.4 the ip of the server where "thelonge" is housed, I put the password, the same as with kiwi and mibbit. Then in config.js I configured webirc oa oassword and the irc unrealircd server. But nothing. I have tried many times, but it always comes up with the ip of the server where it is installed. And so "it's practically useless. Can you help me?

I have the exact same problem. unrealircd conf has webirc block set with the password, thelounge config has the same password set and I'm still getting 127.0.0.1 or the server IP for each user. it's been bugging me for the last week and I cannot figure it out!

**Comment by Tiani91** [comment]
In order to get the webirc socket to work the block in thelounge needs to be matched to the me block in unrealircd.conf so if your server is Irc.BlahBlah.com you will have to input that address into thelounges webirc block and it is case sensitive so it has to match it exactly same with the unrealircd webirc block.for example "Irc.Example.com" <--- unreals name in the me block so in thelounges config.js it would be webirc: { "Irc.Example.com": "linkpass", }, then you would make the unrealircd webirc conf match that as well has to be case sensitive

**Comment by jesusjav** [comment]
is this means that to make thelounge work in multi server connection, i need to know password for every single net, so negociating with ops to get those??

**Comment by mascalzone** [comment]
Exactly. Thelounge must be installed on your vps and consequently must be set in the webirc block for each server. When the server is yours there is no problem. If you want to connect it to another IRC server, you need to know the passwords of the webirc block, otherwise it will connect using the ip of the vps where thelounge is installed. But this is obvious. thelounge, kiwiirc and other clients install when you have an IRC network not to connect to servers not owned by you.

**Comment by jesusjav** [comment]
ah ok thank you for the explanation! so...then for example kiwiirc must know all the webirc server password and they connect  throught webirc protocol right?
