### ISSUE TITLE
Autocomplete button on mobile

### ISSUE THREAD

**Issue by B4rt0** [thelounge/thelounge#3900]
### Feature Description
Optional autocomplete button that would show on mobile devices, next to send button to autocomplete nicknames.

I know that The Lounge supports nickname autocomplete when you prefix it with @, but a button that works the same as TAB key on PC would be much better solution.
Such solution is implemented in [Weechat Android app](https://play.google.com/store/apps/details?id=com.ubergeek42.WeechatAndroid) and as I've used that app for years before moving to The Lounge recently, I can say it's very optimal solution, at least in my personal opinion.

An accompanying option to hide Send button on mobile would be also welcomed (since enter/new line on mobile devices keyboards also serve as send).

**Comment by xPaw** [comment]
Not really sure why adding a dedicated tab button is desired considering completing nicks is not something users do constantly to warrant a dedicated button. It would be somewhat mysterious to users as you need to need to enter beginning of some nick and then press that for something to happen. Especially because no other chat app does this, `@` is already a de-facto standard for autocompletion across the board.

That being said, you can use custom keyboard on your phone that have a dedicated tab button.

**Comment by JacobCarrell** [comment]
For anybody reading this, use @nick instead. The Lounge will strip the @ but give you a list of nicks to autocomplete
