### ISSUE TITLE
Support nickserv password indirection via shell or other command

### ISSUE THREAD

**Issue by rbutoi** [thelounge/thelounge#3908]
### Feature Description
Rather than inlining the password into the user config as plaintext, could a feature be added to call an external command to get the password? This way, the password doesn't need to be exposed in the config file, and the actual mechanism for encrypting the password is handled externally.

This seems like a common solution; it's done in e.g. [mbsync](http://manpages.ubuntu.com/manpages/focal/en/man1/mbsync.1.html#configuration) and [msmtp](http://manpages.ubuntu.com/manpages/focal/man1/msmtp.1.html#configuration%20files) (`PassCmd` and `passwordeval` respectively).

**Comment by xPaw** [comment]
While it is counter intuitive to have plain text IRC passwords in the user file, it is required as it needs to be sent to the IRC server as plain text.

What you are suggesting would _technically_ work, but realistically it's such a niche feature request that I don't see the need to have this in The Lounge out of the box.

That being said, if you are worried about passwords, the next release (current master) supports SASL EXTERNAL which works based on the TLS client certificate, and you don't need to store the password.

**Comment by rbutoi** [comment]
Thank you for the quick response.

Shelling out to gpg or [passwordstore](https://www.passwordstore.org/) is pretty normal and is the most recommended way to access auth passwords programmatically (that doesn't store the password unencrypted) from what I've seen.

I may try to implement this myself; if it's good enough, would you be willing to look at the PR? Reading the discussion on #646 it seems the complications are mostly around file permissions and storing of a direct/hashed representation of the password itself. If there were a `passwordeval` equivalent (of course, as an additional option), none of that would be an issue.

**Comment by xPaw** [comment]
The problem is that it's a solution heavily dependant on being a guru on knowing how to configure this (and not entirely cross platform). It breaks all kinds of flows in the code (even being able to edit the password in the UI).

It's just not a good solution (and there is unlikely a good one). [ZNC does the same thing](https://wiki.znc.in/FAQ#My_NickServ_password_is_stored_in_plaintext.21) with plain text passwords. If you don't trust your machine to store the password (you can still intercept if desired when shelling out or providing via env), I don't think there's any saving you.

**Comment by dgw** [comment]
If at-rest data encryption is important to you, encrypt the whole filesystem and don't worry about individual files. That gives you broader protection against hardware compromise (i.e. theft) anyway.
