### ISSUE TITLE
Nickname dissapear

### ISSUE THREAD

**Issue by chileno28** [thelounge/thelounge#3924]
Hello i just try to translate the lounge and i think i delete something in bundle.js

![111111eew](https://user-images.githubusercontent.com/65797213/82719368-f6919a00-9c77-11ea-8f74-54e7e54a27c1.png)

Please helpme

![111111eew](https://user-images.githubusercontent.com/65797213/82719538-82f08c80-9c79-11ea-9382-6f152d50c9ef.png)

**Comment by fnutt** [comment]
There was some work done regarding making The Lounge translatable. Please see [https://github.com/thelounge/thelounge/pull/1271](https://github.com/thelounge/thelounge/pull/1271). However they stopped working on it because The Lounge was being rewritten in Vue.js. It might be smart waiting for this to be implemented. 😄

**Comment by xPaw** [comment]
Don't modify bundle.js. if you are trying to modify the code, modify the source files and compile.
