### ISSUE TITLE
Add ops operation menu for half ops, admins, and owners.

### ISSUE THREAD

**Issue by lzrdking71** [thelounge/thelounge#3965]
### Feature Description

Add ops operation menu for half ops, admins, and owners.  Request is similar to merged pull request #2355.

**Comment by xPaw** [comment]
Can you make a table or something that describes which mode can give what mode to other users.

Then code over here can be modified to add these: https://github.com/thelounge/thelounge/blob/32d39410da096de9f719adc2824d71ff07df45ee/client/js/helpers/contextMenu.js#L224

**Comment by PeGaSuS-Coder** [comment]
I'm using UnrealIRCd and Anope. By default these are the IRCd `prefixes`:
Owner: +qo (`~`)
Admin: +ao (`&`)
Op: +o (`@`)
Halfop: +h (`%`)
Voice: +v (`+`)

If my memory doesn't fail:
__Owner__ can give any status of _Owner_, _Admin_, _Op_, _Halfop_ or _Voice_ to any user in the channel.
__Admin__ can only give status of _Admin_ and below.
__Op__ can give only status of _Op_ and below.
__Halfop__ can only give status of _Halfop_ or below.
As usual, __Voice__ can't give any status to other users.
__Halfops__ or higher can ban anyone from the channel.

I'll update this if I find anything that's not as I'm explaining, since I'm doing all of this from head.

**Comment by xPaw** [comment]
`PREFIX` is likely ordered right? I wonder if we can simply iterate that and compare whatever mode you have set, instead of essentially hardcoding the list.

**Comment by PeGaSuS-Coder** [comment]
Actually I'm in the mobile, but this is what I've got connecting with Quassel (behind ZNC), along with some other parameters:
`PREFIX=(qaohv)~&@%+ are supported by this server`
So, I gues that they're ordered indeed.

**Comment by lzrdking71** [comment]
> I'm using UnrealIRCd and Anope. By default these are the IRCd `prefixes`:
> Owner: +qo (`~`)
> Admin: +ao (`&`)
> Op: +o (`@`)
> Halfop: +h (`%`)
> Voice: +v (`+`)
> 
> If my memory doesn't fail:
> **Owner** can give any status of _Owner_, _Admin_, _Op_, _Halfop_ or _Voice_ to any user in the channel.
> **Admin** can only give status of _Admin_ and below.
> **Op** can give only status of _Op_ and below.
> **Halfop** can only give status of _Halfop_ or below.
> As usual, **Voice** can't give any status to other users.
> **Halfops** or higher can ban anyone from the channel.
> 
> I'll update this if I find anything that's not as I'm explaining, since I'm doing all of this from head.

This looks accurate to me.

**Comment by PeGaSuS-Coder** [comment]
__Small reminder__

If along the `op` commands we want to provide the `muteban` (aka `quiet` on Freenode), this is where things diverge quiet a bit.

__Examples:__
_UnrealIRCd:_ /mode #channel +b `~q:<mask>`
_InspIRCd:_ /mode #channel +b `m:<mask>`
_Charybdis:_ /mode channel +q `$a:<mask>`

**Comment by xPaw** [comment]
Ban masks are out of scope of this issue.

**Comment by xPaw** [comment]
https://www.unrealircd.org/docs/Channel_modes

In @PeGaSuS-Coder's list, it should be just `+q` and `+a` without `o`.
