### ISSUE TITLE
highlights also needs an exclude list

### ISSUE THREAD

**Issue by ssbarnea** [thelounge/thelounge#3994]
Currently it is impossible to silence specific notifications that include your nick because there are no negative-highlight-matches.

We need a list of words to be excluded from notifications that passed the current include list, so we remove the false positives.

Imagine that you have bots that may notify about build status or commit messages made by yourself, and you are high-likely to not want to be notified about your own actions.

**Comment by xPaw** [comment]
> We need a list of words to be excluded from notifications

How would you exclude yourself from bot messages without also disabling mentions completely for your nick?

Do you mean exclude list would be a list of nicks to not get mentions from?

**Comment by Jay2k1** [comment]
My use case would actually need a word list: my thelounge is available at subdomain.jay2k1.com and whenever other users use the file uploader and post urls with this domain, it highlights me. I now use the option to use a different domain for the uploader, but not everyone has another domain I guess.

**Comment by ssbarnea** [comment]
It is very simple. Assuming your nick is foo, you likely have "foo" in the include list.

If bot posts something like "foo commended on..." you only have to add "foo commented" to the exclude list.

I have being using these patterns with Textual for years, they really work well.

**Comment by xPaw** [comment]
Well it certainly could work that way. It would be trivial to add another `highlightRegex` that would be negative match instead.

However looking at my bot, for one it has colors (so you would need to enter colors into the input box, as custom highlights right now do not strip colors when matching), and for example with github actions there's quite a few patterns: "xpaw opened", "xpaw force-pushed", etc...

**Comment by ssbarnea** [comment]
Yep, stripping colors would be desirable. Lucky me I do not have bots with colors. Here is how textual config looks like, maybe it can help us decide how to implement it.
![textual-regex](https://sbarnea.com/ss/Screen-Shot-2020-07-20-14-36-06.22.png)

**Comment by Jay2k1** [comment]
If we bring up Textual, we should also mention that for this very use case, it also has the ability to selectively ignore highlights from nicks/hosts.
![image](https://user-images.githubusercontent.com/2070503/88071943-bf0a7580-cb74-11ea-945f-ee886f7f705d.png)

I agree though that a negative list for highlights has its own right to exist (and is probably a lot easier to implement than selective ignore like pictured above, even that would be desirable too).

Since I already worked on thelounge's highlight code, I could probably give this a shot... I guess we'd go with a comma-separated list again (plain text, not regex), right?
