### ISSUE TITLE
Add ignore user option and ignore list UI side

### ISSUE THREAD

**Issue by mzelenka** [thelounge/thelounge#4097]
Good day,

Thelounge is neat client that will takeover Mibbit and Flash usage, but its missing ignore option. Alot of IRC(s) have ignore option if one of users is disturbing you. (server side is usually /silence +nickname (unrealircd) but alot of clients have ignore option built in. (UI side)

Administrators cant ban all users for disturbing someone (speaking of big irc networks). It would be nice if thelounge can add it.

**Comment by GewoonYorick** [comment]
This is already part of thelounge? /ignore /ignorelist and /unignore - see the help page in the client for more info :)

**Comment by mzelenka** [comment]
Yes there is an ignore option via commands true, but there is no while selecting user nor in channel option.

**Comment by mzelenka** [comment]
![Screenshot_4](https://user-images.githubusercontent.com/53977501/98467719-17728b00-21d7-11eb-886f-bb522b0b810f.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/53977501/98467746-4983ed00-21d7-11eb-96d5-1344f452d1ba.jpg)

Something like this. The lounge can work on mobile and pc, and sometimes users cant type or they dont know how to (yeah i know its 2020). It would be nice if there was dialog option for those users.

**Comment by GewoonYorick** [comment]
Having it in the context menu for a user could indeed be a nice addition.

We already have the "ignorelist" item on the network context menu, since it's network wide it makes more sense to have it there and not in the channel menu.

Remove ignore I'd rather see as an option in the ignore list. (e.g. a remove button behind the "ignored at"), and a "unignore all" button in the top. (The same could be implemented for ban pages)
