### ISSUE TITLE
Malformed user configs explode violently

### ISSUE THREAD

**Issue by xPaw** [thelounge/thelounge#447]
If JSON is incorrect, it seems to be trying to load the file multiple times and printing a stacktrace each time.

**Comment by theSoenke** [comment]
This seems to require some kind of config validation. Maybe [node-convic](https://github.com/mozilla/node-convict) is worth a look

**Comment by maxpoulin64** [comment]
I think simply avoiding retrying in a loop and printing the same error endlessly should be good enough. I don't think we need full blown validation. Most settings will just error gracefully if they are malformed, for example resulting in impossible to connect to nonsense server using nonsense port.

**Comment by astorije** [comment]
Is this issue already in 1.5.0 or did we add this in pre-releases? My guess is that it's been there since beginning of time.
If so, let's remove the 2.0.0 milestone for now or we'll never get to release it.

**Comment by astorije** [comment]
Okay so I did look into it a little bit, and of course it was not what I was expecting...

It would be easy if it was a retry in loop, but it turns out this is how we watch the user folder ([config](https://github.com/thelounge/lounge/blob/3b84e29e4438672dc8b3e353c1dd0a5e5026b2a7/src/clientManager.js#L140-L165), [code](https://github.com/thelounge/lounge/blob/3b84e29e4438672dc8b3e353c1dd0a5e5026b2a7/src/clientManager.js#L140-L165)) 😮

We could create an ignored array to avoid re-parsing broken files, but that would kill the point of auto-loading as file could not be fixed without restarting the server anymore...

So until we do proper file/directory watching on new or changed files (something like [this](https://nodejs.org/docs/latest/api/fs.html#fs_fs_watch_filename_options_listener) or better), there is nothing we can do to get rid of this IMO.
I'm removing the `2.0.0` milestone as fixing this specific issue will require a much bigger work on the `autoload` feature, but hopefully we'll get there someday...

**Comment by xPaw** [comment]
This was fixed in 2.0.0 by using `require` on the config.

**Comment by astorije** [comment]
I actually don't think this has been fixed, per my previous comment.

**Comment by xPaw** [comment]
Yeah you're right, I misread.
