### ISSUE TITLE
add a /health location for checking periodically, e.g. with uptimerobot or uptime-kuma

### ISSUE THREAD

**Issue by iluvatyr** [thelounge/thelounge#4631]
A lot of containers and projects do have a page to check if the service is online and up. 
This is pretty simple to add by just adding a location with the URL  /health.html or /health to thelounge, so that accessing
thelounge.subdomain.com/health would return a 200 html code when up and working in the simplest case. 
It could also report some other status codes when it is up, but somethings wrong, but getting a 200 html code back or server a page that just says "healthy" would be the main thing for checking easily if thelounge is online from the outside, even through a reverseproxy by checking that url periodically. 
That way it can easily be excluded from the nginx access.log and it is just cleaner to use this than just access a random page of thelounge (e.g. the login page)

It is the same like for example the jellyfin project does, see  https://jellyfin.org/docs/general/networking/monitoring.html?q=health

**Comment by pbsds** [comment]
Could also be solved with a Prometheus metrics endpoint

**Comment by brunnre8** [comment]
Closing as EWONTFIX, due to the following reason.
A health endpoint that doesn't actually tell you anything useful is pointless.

TL's IRC functionality can be horribly broken, yet the static /health route would work perfectly fine as it would literally do nothing but test the static router.

You can already achieve that by just accessing the login page, as you mentioned above with the exact same guarantees.
If you want to get rid of the access log spam, fair enough, add your favorite custom query url fragment and filter on that, not harder than the custom config you'd add to filter /health
