### ISSUE TITLE
Add config to prevent username change

### ISSUE THREAD

**Issue by napei** [thelounge/thelounge#4638]
Unless I've missed it somewhere, I can't find a way to prevent my nick from becoming `mynick12` etc after failed reconnections. 

I use IRC/thelounge specifically to idle in servers where my nick has to be the same.

General behaviour would just be if it fails to connect for whatever reason, then don't, or retry. Not sure about that really as it may cause issues with spamming reconnects.

**Comment by brunnre8** [comment]
TL is meant to be connected as much as possible, not loosing any history.

I don't think that we'll cater for such edge cases.

A workaround is to use sasl on networks that support it or for those that don't, add a nickserv identify + ghost in the server command fields in the server settings

**Comment by alpert1** [comment]
> I don't think that we'll cater for such edge cases.

Edge case? Are you kidding me? I have the same problem on every server I'd like to idle in.
Every morning when my router reconnects and gets a new IP address from my ISP, I lose access to all channels and have to manually restore it because thelounge decides to just change my username, which causes the servers to no longer recognize me and deny access to the relevant channels. It's an absurd behavior, which I have not seen from any program I've ever used!


> TL is meant to be connected as much as possible, not loosing any history.

What's the point of being connected to a server if TL's username changes prevents access to the relevant channels? The history is completely lost, as TL can't automatically join the relevant channels with a made up username.


> A workaround is to use sasl on networks that support it or for those that don't, add a nickserv identify + ghost in the server command fields in the server settings

None of the servers support sasl or the nickserv ghost command. TL should not mess with the user name to begin with or at least give the user an option to set this behaviour!

Please fix this issue! I have problems with almost every server I am interacting with and it's making TL barely usable!

**Comment by brunnre8** [comment]
maybe take some of the emotion out...

This is an open source project that you are free to modify if you feel strongly about a feature.

Your seem to use IRC completely differently than I, none of my network work the way you describe, nor does my ISP boot me off my IP each day.

So that's a rather specific situation you are in. And sure, then your priorities are different.

It isn't my priority though.

I'm not saying there's no bug with the nick re grabbing, just needs someone that cares enough to fix it and send a PR.

**Comment by alpert1** [comment]
> Maybe take some of the emotion out...

I think it is understandable that I'm somewhat taken aback by the way in which you dismissed this significant issue as irrelevant and just closed the ticket.

> This is an open source project that you are free to modify if you feel strongly about a feature.

If I knew how, I would.

> You seem to use IRC completely differently than I, none of my networks work the way you describe, nor does my ISP boot me off my IP each day.

It would be great, if TL worked for everyone though.

> So that's a rather specific situation you are in. And sure, then your priorities are different.
> 
> It isn't my priority though.
> 
> I'm not saying there's no bug with the nick re grabbing, just needs someone that cares enough to fix it and send a PR.

Understandable, but please reopen the issue so others will discover it more easily. This problem significantly harms the usability of TL.

**Comment by brunnre8** [comment]
There is no point in reopening the issue.

For one, there is another one still open that is about the buggy nick change behavior.

Second, there's a balance we need to weight in regards to adding options.
TL has a limited number of knobs ever since by design, to keep it simple for users.

Your situation is still a special case. You won't like that, but have you maybe tried to get your server admins to implement basic features on their end?

Having services be able to regain a nick or account based access list with sasl is pretty much the better solution than trying to make the client not connect if the connection drops.

**Comment by Beersteddy** [comment]
Absolutely not a special case. Nick change happens all the time. 
Very randomly actually. On some serves it stay the same, while on the other will change when container restarted (static IP here). Then on the next restart will check the nick on other randomly. There is no consistency when it really happens.

It really should be a simple option to `don't randomise nicknames`

Constantly needs to remove random number at the end of the nick.

![image](https://github.com/thelounge/thelounge/assets/91010735/25076bb7-22d0-4e37-a3de-e561bd462ce9)

**Comment by Beersteddy** [comment]
> There is no point in reopening the issue.
> 
> For one, there is another one still open that is about the buggy nick change behavior.
> 
> Second, there's a balance we need to weight in regards to adding options. TL has a limited number of knobs ever since by design, to keep it simple for users.
> 
> Your situation is still a special case. You won't like that, but have you maybe tried to get your server admins to implement basic features on their end?
> 
> Having services be able to regain a nick or account based access list with sasl is pretty much the better solution than trying to make the client not connect if the connection drops.

Absolutely not a special case. Nick change happens all the time. 
Very randomly actually. On some serves it stay the same, while on the other will change when container restarted (static IP here). Then on the next restart will check the nick on other randomly. There is no consistency when it really happens.

It really should be a simple option to `don't randomise nicknames`

Constantly needs to remove random number at the end of the nick.

![image](https://github.com/thelounge/thelounge/assets/91010735/25076bb7-22d0-4e37-a3de-e561bd462ce9)
