### ISSUE TITLE
CTCP VERSION response handling

### ISSUE THREAD

**Issue by brunnre8** [thelounge/thelounge#4785]
We have a bug open that wants to hide the TL version from ctcp: https://github.com/thelounge/thelounge/issues/1344
As well as a corresponding PR implementing that. The PR also allows sending any garbage response of the admins choice.

However, the reasoning given in the PR while this seems worthwhile is questionable to me.

If one is concerned that people may figure out a security bug in TL by seeing the version, just sending TL without a version doesn't help whatsoever. An attacker can simply play back any known CVE since the beginning of time until one sticks.

Tracking users seems to be a non concern, considering that most will be using the latest release and that's a pretty common string therefore.

Adding garbage there defeats the whole point of ctcp version in the first place and I don't think we should humor that. If people want to do so, they should patch the code.

Now, my personal preference is to remove the ctcp version response altogether.

Responding to external probing without the user giving their consent is not a thing I want any software to do.
I've turned off any ctcp responses but action on both libera and oftc and it works just fine.
All of emersions clients (gamja, soju) don't carry ctcp version and no one complained (and that's the bouncer sr.ht uses with quite the user base).

We stopped doing [finger](https://en.wikipedia.org/wiki/Finger_(protocol)) too and nobody died :wink: people will survive without it.

@MaxLeiter @itsjohncs what is your opinion here?

Essentially here's our options:
1) Keep it as is, ctcp version is useful
2) Allow hiding the version string, stops being useful for any sensible use of the string (security scanning of net ops, support chan)
3) allow full override, as implemented by the PR or something similar.
   The response is now useless for everything it was intended. Can't do scanning as netops, can't use it for support.
4) Stop responding to anything but ctcp action. Trivial to do, solves all the security concerns, principle of least surprise as one can't be probed by random people.

**Comment by dgw** [comment]
1) ZNC has supported overriding the VERSION string (or any other CTCP response) for ages. In your own words, "nobody died" from that either.

2) Some IRC networks _require_ that clients respond to VERSION requests.
What happens to TL users on one of these networks if the VERSION response is completely removed? They can be banned at any time, at the discretion of network staff, for policy violation.

That said, (1) is just a minor point of interest. Only (2) will affect me, because TL has replaced my old ZNC install and at least one network I use daily has "clients must respond to VERSION" as one of its rules.

If you want to make VERSION replies opt-in and have TL ignore those requests _by default_, that's great, as long as the user can turn it back on (as a per-network setting?) if required.

**Comment by gcanosa** [comment]
I guess to keep aligned with RFC and IRC standards it's a good practice to keep the option, and allow the final user to enable or disable the reply, even customize or modify the default CTCP VERSION REPLY.

**Comment by xPaw** [comment]
Just my 2 cents: we can start by removing the version number from the response, without adding any options to show/hide it. This shouldn't break anyone.

**Comment by brunnre8** [comment]
doesn't break anyone but as stated above also has no benefit. Makes the version response mostly useless at which point we can just send nothing

**Comment by MaxLeiter** [comment]
I agree with xPaw. 

> also has no benefit
There's still the user's client, which might have value to someone.
