### ISSUE TITLE
Do not use "facebookexternalhit/1.1 Twitterbot/1.0" in the user agent string

### ISSUE THREAD

**Issue by robrwo** [thelounge/thelounge#4914]
The links plugin `server/plugins/irc-events/link.ts` includes the text "facebookexternalhit/1.1 Twitterbot/1.0". This triggers security filters that see this as fake Facebook or Twitter bots and blocks them.

**Comment by Jay2k1** [comment]
The reason this was added was for link previews (#3602). Can you specify what kind of filters are being triggered by it?

**Comment by robrwo** [comment]
A website I maintain validates known bots, to prevent fake robots claiming to be something they are not, e.g. claiming to be Googlebot.  If the filter sees these bots, it verifies that the request is coming from the network (usually using reverse DNS), and rejects it when not.  Google, Bing, Facebook/Meta, Twitter and others have documented how to verify their bots.

Facebook usually makes HTTP range requests to only request the first 50kb of the file. That makes more sense than using a fake user agent.

As far as I know, most websites will send OpenGraph data to any user agent. You shouldn't need to fake this in order to get that data.

**Comment by Jay2k1** [comment]
> A website I maintain validates known bots, to prevent fake robots claiming to be something they are not, e.g. claiming to be Googlebot. If the filter sees these bots, it verifies that the request is coming from the network (usually using reverse DNS), and rejects it when not. Google, Bing, Facebook/Meta, Twitter and others have documented how to verify their bots.

Interesting approach, haven't heard of that yet. 
According to the PR, Apple uses the same fake UA for its link previews in iMessage, so I'd assume the website in question also does not show link previews there. And you would think that Apple would be much more likely to get big players like twitter and amazon to open their previews to their product than, say, thelounge.
 
> Facebook usually makes HTTP range requests to only request the first 50kb of the file. That makes more sense than using a fake user agent.

Thelounge does the same: https://github.com/thelounge/thelounge/blob/master/defaults/config.js#L153-L161
Yet I don't see how this relates to using a specific UA in order to make certain (big) websites send opengraph tags. The PR mentioned amazon, twitter is another I know from experience. 
In case you misunderstood: We do this not to get smaller versions of the websites, we do this to get opengraph tags *at all*. Try it with a regular browser (incognito) or curl - some of the big websites just don't deliver these tags to any user agent.

> As far as I know, most websites will send OpenGraph data to any user agent. You shouldn't need to fake this in order to get that data.

I completely agree, we shouldn't need to do this. Unfortunately, it appears like we have to though (except we start using UAs domain specific, i.e. `if (domain == amazon.com) ua = this; elseif (domain == twitter.com) ua = that; ...` - but I doubt that maintainers want to maintain such a logic.

**Comment by robrwo** [comment]
I'm aware that Apple uses that technique. And iMessage and others that use fake UA information will still get blocked.

A bit of web searching shows other software dealing with the same issue, e.g. Lemmy.  

It depends on whether you consider it more important to get previews from some major websites or not.

My own take is that faking this information will cause more problems than not. You may want to consider making this an option, since it depends whether the users care enough about getting previews from every site (especially sites like Amazon).

**Comment by Jay2k1** [comment]
> It depends on whether you consider it more important to get previews from some major websites or not.

Personally I'd consider this quite important, yes. Links to major websites are quite likely to cause user confusion (and hence bug reports), and closing each one of them, explaining that it's not our fault, feels like a worse solution than what we and others currently do, won't help the users and would lead to bad UX.

> My own take is that faking this information will cause more problems than not

When we're talking personal opinions: 
- your issue is the first one I've seen that brings up an actual problem with this approach, but I bet if major websites wouldn't have link previews, there'd be a lot more
- I completely agree that it's a hacky workaround that shouldn't be necessary and should be removed if there's an alternative that works equally well (or better)

Sadly, user agents are a mess that involves lots of faking pretty much since they were introduced. If you've ever tried to derive the used browser from the UA string, you'll know what I mean.

---

As for twitter, I checked if mattermost (an open source, self-hosted Slack alternative) does the same, and indeed they used to, but I found out that, according to a [comment from 2021](https://github.com/mattermost/mattermost/pull/17186#issuecomment-808260858), 
> Twitter only responds with OpenGraph metadata when the user agent includes "bot" somewhere in it

So this might be worth testing.

**Comment by Jay2k1** [comment]
Based on quick curl tests, twitter/X responded with og tags for both
`Mozilla/5.0 (compatible; The Lounge IRC Client; +https://github.com/thelounge/thelounge) facebookexternalhit/1.1 Twitterbot/1.0`
and
`'Mozilla/5.0 (compatible; The Lounge IRC Client; +https://github.com/thelounge/thelounge) thelounge-bot`

...while amazon.com didn't supply og tags for either, so we display the *title* and *description* meta tags.

**Comment by robrwo** [comment]
Try adding a Range header as per https://developers.facebook.com/docs/sharing/webmasters/web-crawlers#troubleshooting
```sh
curl -v --compressed -H "Range: bytes=0-524288" -H "Connection: close" \
   -A "Mozilla/5.0 (compatible; The Lounge IRC Client; +https://github.com/thelounge/thelounge) thelounge-bot" \
   $URL
```

**Comment by brunnre8** [comment]
parsing the user agent string is the problem to begin with... your blocklist thingy just makes it worse.
Frankly, just return the same payload to anyone who asks. Changing your behavior based on any sort of UA string is bad and why we pinky swear that we're twitter and why every browser on earth is mozilla.

Just... don't

**Comment by robrwo** [comment]
> parsing the user agent string is the problem to begin with... your blocklist thingy just makes it worse. Frankly, just return the same payload to anyone who asks. Changing your behavior based on any sort of UA string is bad 

Agreed that changing content based on UA strings is bad, but that's what companies like Amazon do.

As someone who maintains a large website that does not do that, we still give unwanted bots get a short rejection message (<1k) vs a larger web page with headers, footers, logos, icons, style sheets etc.  While rate limiting and blocking cloud services like AWS helps, parsing user agent strings is part of that.

It's useful to allow Google to index a website, because it brings some traffic (and paying customers) to the website.
A bot coming from some other network claiming to be Google? Nope. Gets blocked.  (Some of the smaller AI companies to start falsely claiming they are Googlebot after realising that everyone is blocking SleazeCoinAI in the user agent string. I've seen multiple companies do that from the same IP addresses.)

Some companies might allow verified search engine robots to index pages that are normally behind logins, e.g. newspapers.

So this is what's happened to the internet: "information wants to be free" has become "I'm going to resell your information that I got for free" and site operators have to take defensive measures to keep these bots from taking their content, and using too much bandwidth and CPU (which costs them money) at the expense of human users.

**Comment by brunnre8** [comment]
In any casey considering how niche this problem is I'd say patch the code if you want to change the agent string.

Given that nothing is really broken and apple does it to we just keep it as is I'd think.

We identify clearly enough, so you can accept or reject TL as you see fit in your site.
