### ISSUE TITLE
Mention Window

### ISSUE THREAD

**Issue by McGriddle** [thelounge/thelounge#892]
Is it possible to have a window for each connection that keeps track of mentions of your username? I've seen that with other chat clients and wondered if it was possible with thelounge.

**Comment by YaManicKill** [comment]
It's probably something we are unlikely to do anytime soon. However, (and I know I keep saying this) we are planning a plugin system, and this would be able to be done there. However, I'll keep it open just now and see what others think.

**Comment by Cldfire** [comment]
I was going to work on a PR for a Discord-like mention system:

![2017-01-27 08_47_19-what d i miss_ recent mentions feature - youtube](https://cloud.githubusercontent.com/assets/13814214/22372904/49405154-e46d-11e6-873d-e40662c64ed0.jpg)

There are a number of other things that have to be done before that can happen, though, such as the performance of scrollback (#828).

**Comment by YaManicKill** [comment]
@Cldfire That definitely would be a possibility. I would probably prefer it to be something like that than a whole screen itself, as the screens on the left are all actual chats (or lobbies) and I wouldn't want to mess wit hthat too much.

There is, however, #791 that could have the messages in it. But I definitely wouldn't be up for a screen for each server for just notifications.

**Comment by Cldfire** [comment]
The home tab would be certainly be a nice place to put something like that, if / when it becomes a thing.

**Comment by h-rezaei** [comment]
This would make so much sense for screen reader users and accessibility in general. Not just screen reader users but anyone who can't read a lot of text all at once or can't search through a lot of messages.
Anyway, in my case i can explain.
In clients like Instantbird, You could leave the channel messages undeleted. Whenever i wanted to see if  i was mentioned, i would focus on the channel window and use my screen reader's search function to search for my nickname. and since that window kept all of the messages, my reader was able to search the entire messages and  show me if my name has been written.
In the lounge however, I can't do that, because the browser doesn't load all the messages at once; you have to scroll upwards for them to show up, and whenn you do it clips the earlyer messages out of view if i'm not mistaking. Anyway because of that my software ccan't search a lot of messages and i basically have to read all the messages from bottom to top to find where i was mentioned.
Will be waiting for this whenever it gets worked on  :)
